#!/usr/bin/env bash
# Useing a while loop to display "Best School" 10 times

count=0

while [ $count -lt 10 ]; do
    if [ $count -eq 8 ]; then
	echo "Best School"
	echo "Hi"
    else
	echo "Best School"
    fi
    ((count++))
done
