#!/usr/bin/env bash
# This srcipt configures the hosts file to resolve localhost and facebook.com
as specified

if [ -f "/.dockerenv" ]; then
    echo "Running on Docker, proceeding with configuration..."
else
    echo "This script id intended to run on Docker only."
    exit 1
fi

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

echo "Hosts file configured successfully."
